import 'package:big_break_mobile/features/evening_plan/presentation/evening_plan_data.dart';

const testPremiumEveningRouteId = 'r-date-noir';

const testCozyEveningRoute = EveningRouteData(
  id: 'r-cozy-circle',
  title: 'Тёплый круг на Покровке',
  vibe: 'Камерный вечер',
  blurb: 'Аперитив, лёгкий стендап и долгий разговор в кофейне',
  totalPriceFrom: 1400,
  totalSavings: 650,
  durationLabel: '19:00 — 00:30',
  area: 'Чистые пруды → Покровка',
  goal: EveningGoal.newfriends,
  mood: EveningMood.chill,
  budget: EveningBudget.mid,
  hostsCount: 8,
  steps: [
    EveningRouteStep(
      id: 'step-brix',
      time: '19:00',
      endTime: '20:10',
      kind: EveningStepKind.bar,
      title: 'Аперитив в Brix Wine',
      venue: 'Brix Wine',
      address: 'Покровка 12',
      emoji: '🍇',
      distance: '0.6 км',
      walkMin: 7,
      perk: 'Бронируем в приложении — стол держим до начала встречи',
      perkShort: 'Перк',
      ticketPrice: 800,
      description: 'Тихий старт за бокалом и знакомством.',
      vibeTag: 'Спокойно',
      lat: 55.7601,
      lng: 37.6393,
    ),
    EveningRouteStep(
      id: 'step-standup',
      time: '20:30',
      endTime: '22:00',
      kind: EveningStepKind.show,
      title: 'Открытый микрофон Standup Store',
      venue: 'Standup Store',
      address: 'Маросейка 7',
      emoji: '🎤',
      distance: '0.8 км',
      walkMin: 9,
      lat: 55.7587,
      lng: 37.6344,
    ),
    EveningRouteStep(
      id: 'step-zarya',
      time: '22:30',
      endTime: '00:30',
      kind: EveningStepKind.afterparty,
      title: 'After-chat в Кафе Заря',
      venue: 'Кафе Заря',
      address: 'Покровка 20',
      emoji: '☕',
      distance: '0.4 км',
      walkMin: 5,
      lat: 55.7591,
      lng: 37.6412,
    ),
  ],
);

const testPremiumEveningRoute = EveningRouteData(
  id: testPremiumEveningRouteId,
  title: 'Свидание Noir',
  vibe: 'Вечер для двоих',
  blurb: 'Камерный показ, прогулка и финал на крыше',
  totalPriceFrom: 2400,
  totalSavings: 900,
  durationLabel: '20:00 — 01:00',
  area: 'Парк Горького → Берсеневская',
  goal: EveningGoal.date,
  mood: EveningMood.date,
  budget: EveningBudget.high,
  premium: true,
  hostsCount: 3,
  steps: [
    EveningRouteStep(
      id: 'premium-cinema',
      time: '20:00',
      kind: EveningStepKind.show,
      title: 'Авторское кино в Garage Screen',
      venue: 'Garage Screen',
      address: 'Крымский Вал 9',
      emoji: '🎬',
      distance: '0.5 км',
      lat: 55.7359,
      lng: 37.6012,
    ),
    EveningRouteStep(
      id: 'premium-dinner',
      time: '22:00',
      kind: EveningStepKind.dinner,
      title: 'Ужин в Tilda Bistro',
      venue: 'Tilda Bistro',
      address: 'Берсеневская 6',
      emoji: '🍝',
      distance: '1.2 км',
      lat: 55.7441,
      lng: 37.6092,
    ),
  ],
);
