platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
ENV['YANDEX_MAPKIT_VARIANT'] = 'full'

inhibit_all_warnings!

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def move_privacy_manifest_to_resources(target)
  return unless target.respond_to?(:source_build_phase)
  return unless target.respond_to?(:resources_build_phase)

  source_phase = target.source_build_phase
  resources_phase = target.resources_build_phase
  return unless source_phase && resources_phase

  source_phase.files.dup.each do |build_file|
    file_ref = build_file.file_ref
    next unless file_ref&.path&.end_with?('PrivacyInfo.xcprivacy')

    source_phase.remove_build_file(build_file)
    already_resource = resources_phase.files.any? do |resource_file|
      resource_file.file_ref == file_ref
    end
    resources_phase.add_file_reference(file_ref) unless already_resource
  end
end

def remove_empty_firebase_core_dummy_source(target)
  return unless target.name == 'firebase_core'
  return unless target.respond_to?(:source_build_phase)

  target.source_build_phase.files.dup.each do |build_file|
    file_ref = build_file.file_ref
    next unless file_ref&.path&.end_with?('/dummy.m')

    target.source_build_phase.remove_build_file(build_file)
  end
end

target 'Runner' do
  use_frameworks!

  pod 'YandexLoginSDK', '~> 3.1'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    move_privacy_manifest_to_resources(target)
    remove_empty_firebase_core_dummy_source(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      existing_definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
      existing_definitions = [existing_definitions] unless existing_definitions.is_a?(Array)
      permission_definitions = [
        'PERMISSION_CAMERA=1',
        'PERMISSION_CONTACTS=1',
        'PERMISSION_LOCATION=1',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_PHOTOS=1',
      ]
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] =
        (existing_definitions + permission_definitions).uniq
      # Third-party pods currently emit noisy warnings in Xcode 26.x.
      # Keep warnings enabled for Runner, but silence them inside Pods.
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SUPPRESS_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      other_swift_flags = config.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
      unless other_swift_flags.include?('-disable-autolink-framework')
        config.build_settings['OTHER_SWIFT_FLAGS'] = "#{other_swift_flags} -Xfrontend -disable-autolink-framework -Xfrontend AppIntents"
      end
    end
  end
end
